### PR TITLE
frontend: SettingsMenu: Add feedback and increase timeouts

### LINKED ISSUE #2820: core: frontend: "remove logs" does not give any feedback
### Current behaviour

When deleting a log, there is no feedback that the logs are being deleted.  The window closes, but when opened again, the logs still appear there, confusing the user.

image

### Expected or desired behaviour

There should be some kind of "deleting" or "loading" thingy to let users know that the logs are deleting.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### LINKED ISSUE #2821: bug: log files do not remove
### Bug description

Logs do not remove after pressing "remove" and rebooting the pi.

### Steps to reproduce

- Removed logs (745.8MB shown)
- Rebooted
- No logs shown
- Waited 5min
- Downloaded logs
- 681mb of logs were downloaded

Before removing:
image

After reboot:
image

### Primary pain point(s)

_No response_

### Additional context

_No response_

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by JoaoMario109**
Since currently no user feedback is given when performing operations, this PR adds an overlay with information about current operation and in case of errors add an alert at the top of the settings menu to make clear to user that operation was not successful.

Feedback provided for user:
image

Closes #2820

As the timeouts were shorts most of remove operations were failing, so timeouts for removing logs and reset were increased.

Probably fix #2821 by timeout increasing

### CODE REVIEW

File: core/frontend/src/components/app/SettingsMenu.vue [hunk 1]
```diff
@@ -144,12 +159,17 @@ import { commander_service } from '@/types/frontend_services'
 import back_axios from '@/utils/api'
 import { prettifySize } from '@/utils/helper_functions'
 
+import SpinningLogo from '../common/SpinningLogo.vue'
```
Comment (patrickelectric) [inline core/frontend/src/components/app/SettingsMenu.vue:162]: Can we use @ for absolute reference ?

**Review by patrickelectric — APPROVED** [review]

File: core/frontend/src/components/app/SettingsMenu.vue (hunk 1 above)
Comment (JoaoMario109) [reply core/frontend/src/components/app/SettingsMenu.vue]: Done!
