### PR TITLE
core: frontend: Fixes unable to continue in wizard

### LINKED ISSUE #2395: wizard: `No parameters available for this setup`, but cannot `CONTINUE`.
https://github.com/bluerobotics/BlueOS/assets/5920286/8d30079c-d403-4097-a320-96a5f2da475f

Fresh 1.1.1 install, on a Raspberry Pi 3. Pixhawk was disconnected.

### PR DESCRIPTION
**Pull request by JoaoMario109**
Removes the blocking behavior in the setup wizard encountered when `No parameters available for this setup' is displayed.
Fixes #2395

### CODE REVIEW

**Comment by Williangalvani** [comment]
hmm... 

while this fixes the issue, I'm not sure it is the best fix.
that code was like that in order to make the user interact with that dropdown. So they wouldn't just click next without loading the proper param set.

There is an option called "Do not load default parameters", which should be selectable in these situations.

I think the underlying issue is the `is_loading()` computed, which is hanging trying to wait for a board to be detected, as there is no board present.

File: core/frontend/src/components/wizard/DefaultParamLoader.vue [hunk 1]
```diff
@@ -172,6 +188,15 @@ export default Vue.extend({
         throw error
       }
     },
+    onLoadingTimeout() {
+      if (this.is_loading) {
+        this.loading_timeout_reached = true
+
+        if (this.selected_param_set_name === '') {
+          this.selected_param_set_name = this.not_load_default_params_option
+        }
```
Comment (joaoantoniocardoso) [inline core/frontend/src/components/wizard/DefaultParamLoader.vue:197]: nice touch :)

Comment (joaoantoniocardoso) [reply core/frontend/src/components/wizard/DefaultParamLoader.vue:197]: Can we do the same and skip the loading time when `invalid_board_or_version`? (maybe in another PR, since it's a different thing)

**Review by joaoantoniocardoso — APPROVED** [review]
I couldn't find your dockerhub to test, but looks good to me.

**Comment by Williangalvani** [comment]
> I couldn't find your dockerhub to test, but looks good to me.

For context: we have an action that deploys the branch to a container 
you need to add DOCKER_USERNAME and DOCKER_PASSWORD secrets to your fork and enable github actions there.

**Comment by joaoantoniocardoso** [comment]
> > I couldn't find your dockerhub to test, but looks good to me.
> 
> For context: we have an action that deploys the branch to a container you need to add DOCKER_USERNAME and DOCKER_PASSWORD secrets to your fork and enable github actions there.

Err.. Better to do that, the image on his dockerhub (joaomariolago) is crashing my Raspberry.

**Review by patrickelectric — APPROVED** [review]
