### PR TITLE
Fix priority changing on Bookworm

### LINKED ISSUE #3086: bookworm network priority changes is duplicating routes instead of replacing them

### PR DESCRIPTION
**Pull request by Williangalvani**
to test the routing, use `watch ip route`, then change it in the UI.

this is now also always using the settings file as a source of truth, instead of randomly accepting the current state and saving it to the settings file.

fix #3086 

tested on bookworm and bullseye

## Summary by Sourcery

Fix interface priority issues on Debian Bookworm.

Bug Fixes:
- Fix priority changing on Bookworm.

Enhancements:
- Always use the settings file as the source of truth for network configuration, rather than randomly accepting the current state and saving it.

Tests:
- Tested on Bookworm, needs testing on Bullseye.

### CODE REVIEW

File: core/frontend/src/components/app/NetworkInterfacePriorityMenu.vue [hunk 1]
```diff
@@ -140,16 +140,20 @@ export default Vue.extend({
...
         method: 'post',
         url: `${ethernet.API_URL}/set_interfaces_priority`,
         timeout: 10000,
-        data: interface_priority,
+        data: interface_priorities,
       })
         .catch((error) => {
-          const message = `Could not increase the priority for interface '${interface_priority}', ${error}.`
+          const message = `Could not set network interface priorities: ${interface_priorities}, error: ${error}`
+          console.log(interface_priorities)
```
Comment (JoaoMario109) [inline core/frontend/src/components/app/NetworkInterfacePriorityMenu.vue:156]:
```suggestion
```

**Review by JoaoMario109 — CHANGES_REQUESTED** [review]

**Review by JoaoMario109 — APPROVED** [review]

**Review by patrickelectric — APPROVED** [review]
