### PR TITLE
frontend: version-chooser: link to GitHub Releases when available versions fetch fails

### LINKED ISSUE #1502: core: frontend: Version Chooser should link to the github releases page if it cannot connect to dockerhub
### Current behaviour

When version chooser fails to get the versions list from dockerhub it currently just provides the error, which is not very helpful for people who want an update and don't know where new versions can be found.

Case in point: https://discuss.bluerobotics.com/t/blueos-equivalent-of-companion-routing/13662/3

### Expected or desired behaviour

While ideally fetching images would never fail (and we should perhaps investigate why it's not so rare that it does), it's unreasonable to assume that an external API will _always_ be available when anyone wants it.

It would be useful if a link to the BlueOS releases list on GitHub was provided as a fallback, perhaps along with some instructions for how to install a version manually (since it needs to be unzipped). I guess those instructions could be provided in our docs, in which case we could just provide a link to the relevant docs section, which could then further link to the relevant GitHub section.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by nicoschmdt**
fix #1502 

image

## Summary by Sourcery

Clarify manual image upload options and provide alternative download instructions when fetching available versions fails.

New Features:
- Link to GitHub Releases as an alternative source when available version retrieval fails.
- Add a tooltip to the Manual upload section explaining hardware architecture requirements for .tar artifacts.
- Include GitHub Releases as an additional source for downloadable .tar docker images in the Manual upload instructions.

Documentation:
- Improve in-app guidance for manually downloading and uploading BlueOS image artifacts, including architecture selection and alternative download locations.

### CODE REVIEW

File: core/frontend/src/components/version-chooser/VersionChooser.vue [hunk 1]
```diff
@@ -113,6 +113,17 @@
           dark
         >
           {{ available_versions.error }}
+          <br><br>
+          You can download BlueOS versions directly from
```
Comment (ES-Alexander) [inline core/frontend/src/components/version-chooser/VersionChooser.vue]:
```suggestion
          You can download BlueOS versions (`BlueOS-core-docker-image` files) directly from the Assets in
```

File: core/frontend/src/components/version-chooser/VersionChooser.vue [hunk 2]
```diff
@@ -153,12 +164,35 @@
...
+          <template #activator="{ on }">
+            <v-icon
+              small
+              v-on="on"
+            >
+              mdi-information-outline
+            </v-icon>
+          </template>
+          <span>
+            When selecting the .tar artifact, make sure it matches your hardware architecture (amd64, armv7, or arm64)
```
Comment (ES-Alexander) [inline core/frontend/src/components/version-chooser/VersionChooser.vue]:
```suggestion
            When selecting the .tar artifact, make sure it matches your hardware architecture (armv7, arm64, or amd64)
```
In this case I think it's preferable to order by hardware usage likeliness rather than lexicographically. That way an uncertain user is more likely to get the correct image first try.

File: core/frontend/src/components/version-chooser/VersionChooser.vue [hunk 3]
```diff
@@ -153,12 +164,35 @@
...
-      >Github's CI</a>
+        rel="noopener noreferrer"
+      >
+        Github's CI</a>,
+      <a
+        href="https://github.com/bluerobotics/BlueOS/releases"
+        target="_blank"
+        rel="noopener noreferrer"
+      >
+        GitHub Releases</a>
```
Comment (ES-Alexander) [inline core/frontend/src/components/version-chooser/VersionChooser.vue]: > These can be downloaded from the BlueOS [Releases](https://github.com/bluerobotics/BlueOS/releases) Assets, or [CI](https://github.com/bluerobotics/BlueOS/actions/workflows/test-and-deploy.yml) Artifacts (GitHub account required), or generated locally using `docker save`.

In order of most to least user friendly.

File: core/frontend/src/components/version-chooser/VersionChooser.vue [hunk 4]
```diff
@@ -113,6 +113,17 @@
...
+          You can download BlueOS versions (`BlueOS-core-docker-image` files) directly from the Assets in
+          <a
+            href="https://github.com/bluerobotics/BlueOS/releases"
+            target="_blank"
+            class="white--text"
+            rel="noopener noreferrer"
+          >
+            GitHub Releases
+          </a>
+          and upload them using the "Manual Upload" section below.
```
Comment (ES-Alexander) [inline core/frontend/src/components/version-chooser/VersionChooser.vue]:
```suggestion
            GitHub Releases</a> and upload them using the "Manual Upload" section below.
```
Currently showing up with the link including the space after Releases:
Image

File: core/frontend/src/components/version-chooser/VersionChooser.vue [hunk 5]
```diff
@@ -153,13 +164,36 @@
       max-width="900"
       class="mx-auto pa-4"
     >
-      <h2>Manual upload</h2>
-      Use this to upload a .tar docker image. These can be downloaded from
+      <h2>
+        Manual upload
```
Comment (ES-Alexander) [inline core/frontend/src/components/version-chooser/VersionChooser.vue]:
```suggestion
        Manual Upload
```
Good to match what the other message says to go to 😅

**Review by patrickelectric — APPROVED** [review]
