### PR TITLE
core: ArdupilotManager: allow setting the SITL frame

### LINKED ISSUE #2094: all SITL instances are using "vectored" models
This means rover, copter, and place code will try to fly (the simplified physics of) an ROV, which doesn't work great (or at all)

### PR DESCRIPTION
**Pull request by Williangalvani**
without this, all SITL instances try to use the "vectored" sub model, which doesn't work great with rover(and others) code.

fix #2094, we'd still need a ui update though

### CODE REVIEW

**Review by rafaellehmkuhl — APPROVED** [review]
Haven't tested, but the code looks good to me.

File: core/services/install-services.sh [hunk 1]
```diff
@@ -35,6 +34,7 @@ SERVICES=(
     ping
     versionchooser
     wifi
+    ardupilot_manager # ardupilot_manager's setup.py requires the dependencies it is supposed to install...
```
Comment (patrickelectric) [inline core/services/install-services.sh:37]: how so ? ardupilot_manager does not have direct dependency to the others services.

File: core/services/ardupilot_manager/ArduPilotManager.py [hunk 2]
```diff
@@ -257,10 +257,25 @@ def start_serial(self, board: FlightController) -> None:
...
+        self.configuration["sitl_frame"] = frame
+        self.settings.save(self.configuration)
+
+    def load_sitl_frame(self) -> SITLFrame:
+        if self.settings.sitl_frame != SITLFrame.UNDEFINED:
+            return self.settings.sitl_frame
+        frame = SITLFrame.VECTORED
+        logger.warning(f"SITL frame is undefined. Setting {frame} as current frame.")
+        self.configuration["sitl_frame"] = frame
+        self.settings.save(self.configuration)
```
Comment (patrickelectric) [inline core/services/ardupilot_manager/ArduPilotManager.py:271]:
```suggestion
        self.set_sitl_frame(frame)
```

**Review by patrickelectric — CHANGES_REQUESTED** [review]

File: core/services/install-services.sh (hunk 1 above)
Comment (Williangalvani) [reply core/services/install-services.sh:37]: setup.py tries to use our settings service, which requires pydantic

Comment (patrickelectric) [reply core/services/install-services.sh:37]: And that'll be installed by setup.py on the following loop. My questions is, why the order of ardupilot_manager was changed since there is no dependency to others services.

Comment (Williangalvani) [reply core/services/install-services.sh]: this is the reason:
https://github.com/bluerobotics/BlueOS/actions/runs/6176088878/job/16764395632?pr=2093#step:7:12948

I'm open to alternative solutions

Comment (patrickelectric) [reply core/services/install-services.sh]: Check here: https://github.com/bluerobotics/BlueOS/blob/master/core/services/install-services.sh#L41

Comment (Williangalvani) [reply core/services/install-services.sh]: updated

**Review by patrickelectric — APPROVED** [review]
